### ISSUE TITLE
上传文件时，总是返回-97

### ISSUE THREAD

**Issue by wjzheng** [tencentyun/wecos-ugc-upload-demo#1]
在使用这个demo的过程中，一直返回-97，签名错误的code；

使用场景：
  服务端获取签名使用到的是：COS-AUTH——COS鉴权服务器DEMO
  Cos版本:v4
  服务器域名的设置以及相关的appid的配置都是正确的，但是就是上传到cos的时候，一直返回-97

**Comment by Jinqn** [comment]
这里是 cos v4 接口返回错误码的介绍：
https://www.qcloud.com/document/product/436/6059
你看看是不是签名计算有问题？测试一下是否 encodeURIComponent 导致的错误。
另外，签名内容里的 expired 字段格式是 0 或 超时的时间戳，例如 60 秒后失效：
```javascript
expired = parseInt(Date.now() / 1000) + 60;
```

**Comment by YinshawnRao** [comment]
能否提供一下错误的签名？

**Comment by wjzheng** [comment]
有fileid
a=wxa9b06acef48c95be&k=AKIDKbhcLtgSUL0dMxni183nLtL7lEVghXEP&e=0&t=1484562428&r=2960574771&f=%2Fwxa9b06acef48c95be%2Fkimbo%2Falbum&b=kimbo
加密之后：
gmCrcfIMSd4l6wUDR/3EXMbCCmlhPXd4YTliMDZhY2VmNDhjOTViZSZrPUFLSURLYmhjTHRnU1VMMGRNeG5pMTgzbkx0TDdsRVZnaFhFUCZlPTAmdD0xNDg0NTYyNDI4JnI9Mjk2MDU3NDc3MSZmPSUyRnd4YTliMDZhY2VmNDhjOTViZSUyRmtpbWJvJTJGYWxidW0mYj1raW1ibw==
file为空
a=wxa9b06acef48c95be&k=AKIDKbhcLtgSUL0dMxni183nLtL7lEVghXEP&e=1484562615&t=1484562555&r=2596033857&f=&b=kimbo
GB5CVSk5RCb8j4mPsmt7g60V3udhPXd4YTliMDZhY2VmNDhjOTViZSZrPUFLSURLYmhjTHRnU1VMMGRNeG5pMTgzbkx0TDdsRVZnaFhFUCZlPTE0ODQ1NjI2MTUmdD0xNDg0NTYyNTU1JnI9MjU5NjAzMzg1NyZmPSZiPWtpbWJv

**Comment by YinshawnRao** [comment]
appid不是数字吗？
appid可以在COS控制台-密钥管理查看

这里的注释可能不是很完善，这个appid是COS的appid，不是小程序的appid

**Comment by wjzheng** [comment]
Yes，appid是数字，是我把小程序的appid和cos的appid搞混了，明天我再试试看，谢谢了。

**Comment by wjzheng** [comment]
问题已经解决，是appid设置的问题。
