### ISSUE TITLE
上传图片一直提示403

### ISSUE THREAD

**Issue by Shawn-Cui** [tencentyun/wecos-ugc-upload-demo#3]
![image](https://user-images.githubusercontent.com/20104130/34930855-99ee3814-fa06-11e7-9e44-73ec7bcb12f6.png)
鉴权服务器应该是没有问题的，我用web尝试可以上传成功

**Comment by Shawn-Cui** [comment]
@Galen-Yip @YinshawnRao @carsonxu

**Comment by carsonxu** [comment]
应该是鉴权问题。
推荐使用XML接口，最大支持50GB，sdk:
https://github.com/tencentyun/cos-wx-sdk-v5

**Comment by Shawn-Cui** [comment]
@carsonxu 似乎不是，我看了下，可能是region的原因，上海地区应该是'sh'吧？受之前web的影响，我写成'ap-shanghai'了

**Comment by carsonxu** [comment]
了解了，这个是调用JSON接口的，region是sh、gz这样的格式。
推荐使用XML接口的工具和SDK，我们近期补充一个XML API的demo，好做统一。

**Comment by Shawn-Cui** [comment]
@carsonxu 这个鉴权服务不能用JavaScript SDK快速入门里面提供的那个签名例子吗？
还有，小程序那边我当月已经修改服务器设置达到5次了，你们官方有没有办法帮忙修改下服务器配置，因为这个月要上线，下个月已经来不及了
谢谢

**Comment by carsonxu** [comment]
那个是 XML API 的签名，XML 和 JSON 签名、region接口都不一致，所以还是推荐使用 https://github.com/tencentyun/cos-wx-sdk-v5

另一个方案是，如果你只用到上传，不想引用很大的 SDK，你可以参考这个 Web 不使用 SDK 直传的 demo，Form 表单的例子，把里面的 ajax 改成 wx.request 和 wx.uploadFile 实现，改过来挺简单的：
https://cloud.tencent.com/document/product/436/9067#.E6.96.B9.E6.A1.88-b.EF.BC.9A.E4.BD.BF.E7.94.A8-form-.E8.A1.A8.E5.8D.95.E4.B8.8A.E4.BC.A0

**Comment by Shawn-Cui** [comment]
@carsonxu 好的，谢谢，我去看下

**Comment by carsonxu** [comment]
不使用 SDK 的例子已增加，项目里面 /server 目录下附带有签名例子
https://github.com/tencentyun/cos-wx-sdk-v5/blob/master/demo/pages/index/index.js#L17-L78

**Comment by Shawn-Cui** [comment]
@carsonxu 成功解决了上传的问题，太感谢了！

**Comment by Shawn-Cui** [comment]
@carsonxu 但是有个问题，成功上传之后好像拿不到文件的路径，返回的结果data为空
![image](https://user-images.githubusercontent.com/20104130/34971982-72783e34-fab9-11e7-97b5-b573370b87ca.png)
还有上传的时候能够指定文件名吗？

**Comment by carsonxu** [comment]
formData里的key就是文件名，url自己拼接就行: prefix + Key
