### ISSUE TITLE
提交后报MalformedPOSTRequest错误

### ISSUE THREAD

**Issue by xiedarin** [tencentyun/wecos-ugc-upload-demo#4]
错误原因 该POST请求的Body内容不合法
我看了下官方的 js的sdk body部分是直接将文件流提交过去的，
而小程序uploadFile,需要设置name 应该是作为参数提交过去的。
应该是这个问题，不知作者如何解决的

**Comment by carsonxu** [comment]
怎么不使用 https://github.com/tencentyun/cos-wx-sdk-v5

**Comment by xiedarin** [comment]
好的，明天再看下

**Comment by carsonxu** [comment]
[XML SDK](https://github.com/tencentyun/cos-wx-sdk-v5) 里面更新了一个不使用 SDK 的简单上传 demo：
https://github.com/tencentyun/cos-wx-sdk-v5/blob/master/demo/pages/index/index.js#L17-L78
完整版本可以用：https://github.com/tencentyun/cos-wx-sdk-v5
